export const GET_JOBS = 'GET_JOBS';
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS';
export const GET_JOBS_FAILURE = 'GET_JOBS_FAILURE';
export const CLEAR_JOBS = 'CLEAR_JOBS';
export const SHOW_DETAILS = 'SHOW_DETAILS';

export const LOAD_MORE_JOBS_SUCCESS = 'LOAD_MORE_JOBS_SUCCESS';
export const LOAD_MORE_JOBS_FAILURE = 'LOAD_MORE_JOBS_FAILURE';